/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Inicio.java
 *
 * Created on 09-mar-2013, 15:38:04
 */
package gui.internal;

import gui.dialog.ContPedidoUI;
import gui.dialog.ContReservaUI;
import gui.dialog.PedConsultaUI;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;

/**
 *
 * @author Ivan C
 */
public class ContabilidadUI extends javax.swing.JPanel {

    /**
     * Creates new form Inicio
     */
    public ContabilidadUI() {
        initComponents();
        
        this.jButton2.setVisible(false);
        
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jButtonPedPag = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(871, 680));
        setMinimumSize(new java.awt.Dimension(871, 680));

        jButton2.setText("Reservas");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButtonPedPag.setText("Pedidos");
        jButtonPedPag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPedPagActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jLabel2.setText("Contabilidad");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(281, 281, 281)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButtonPedPag, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(489, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel2)
                .addGap(88, 88, 88)
                .addComponent(jButtonPedPag, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(375, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPedPagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPedPagActionPerformed
        this.removeAll();
        validate();
        updateUI();

        ContPedidoUI pedconD;
        try {
            pedconD = new ContPedidoUI();

            this.add(pedconD);
            pedconD.setBounds(0, 0, this.getSize().width, this.getSize().height);
            pedconD.setVisible(true);
            this.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(PedidosUI.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("no genera ventana nueva");
        }
        

    }//GEN-LAST:event_jButtonPedPagActionPerformed

    
     public void ashMientrasTanto() {
        this.removeAll();
        validate();
        updateUI();

        ContPedidoUI contpedido;
        try {
            contpedido = new ContPedidoUI();
            this.add(contpedido);
            contpedido.setBounds(0, 0, this.getSize().width, this.getSize().height);
        } catch (Exception ex) {
            Logger.getLogger(PedidosUI.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("no genera ventana nueva");
        }
    }
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.removeAll();
        validate();
        updateUI();

        ContReservaUI resconD;
        try {
            resconD = new ContReservaUI();
            this.add(resconD);
            resconD.setBounds(0, 0, this.getSize().width, this.getSize().height);
        } catch (Exception ex) {
            Logger.getLogger(PedidosUI.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("no genera ventana nueva");
        }        // TODO add your handling code here:
        
    

   
    }//GEN-LAST:event_jButton2ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonPedPag;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
