/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Inicio.java
 *
 * Created on 09-mar-2013, 15:38:04
 */
package gui.internal;

import gui.dialog.PedConsultaUI;
import gui.dialog.PedNewD;
import gui.dialog.ReserConsultaUI;
import gui.dialog.ReserNewD;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;

/**
 *
 * @author Ivan C
 */
public class PedidosUI extends javax.swing.JPanel {

    /** Creates new form Inicio */
    public PedidosUI() {
        initComponents();
        System.out.println("crea");

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newreservabut = new javax.swing.JButton();
        buscartodobut = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jTextField1 = new javax.swing.JTextField();
        newreservabut1 = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(871, 680));
        setMinimumSize(new java.awt.Dimension(871, 680));

        newreservabut.setText("Nueva Reserva");
        newreservabut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newreservabutActionPerformed(evt);
            }
        });

        buscartodobut.setText("Buscar Todas");
        buscartodobut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscartodobutActionPerformed(evt);
            }
        });

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Buscar Por");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cedula Cliente", "Codigo Reserva", "Usuario" }));

        jTextField1.setToolTipText("Hola");

        newreservabut1.setText("Nuevo Pedido");
        newreservabut1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newreservabut1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(newreservabut1)
                        .addGap(223, 223, 223)
                        .addComponent(newreservabut)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(145, 145, 145)
                                .addComponent(jLabel1)
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(42, 42, 42))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(buscartodobut, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jSeparator1)))
                        .addGap(250, 250, 250))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newreservabut1)
                    .addComponent(newreservabut))
                .addGap(28, 28, 28)
                .addComponent(buscartodobut)
                .addGap(31, 31, 31)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(403, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

private void newreservabutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newreservabutActionPerformed

    ReserNewD wres = new ReserNewD();
    wres.setSize(740,520);
    wres.setLocationRelativeTo(null);
    wres.setVisible(true);

}//GEN-LAST:event_newreservabutActionPerformed

private void buscartodobutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscartodobutActionPerformed
    this.removeAll();
    validate();
    updateUI();

    PedConsultaUI pedconD;
    try {
        pedconD = new PedConsultaUI(0, "");

        this.add(pedconD);
        pedconD.setBounds(0, 0, this.getSize().width, this.getSize().height);
    } catch (Exception ex) {
        Logger.getLogger(PedidosUI.class.getName()).log(Level.SEVERE, null, ex);
        System.out.print("no genera ventana nueva");
    }

    // TODO add your handling code here:
}//GEN-LAST:event_buscartodobutActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    this.removeAll();
    validate();
    updateUI();
    try {
        PedConsultaUI pedconD = new PedConsultaUI(jComboBox1.getSelectedIndex(), "" + jTextField1.getText());
        this.add(pedconD);
        pedconD.setBounds(0, 0, this.getSize().width, this.getSize().height);
    } catch (Exception ex) {
        System.out.print("no genera ventana nueva");
    }
// TODO add your handling code here:
}//GEN-LAST:event_jButton1ActionPerformed

private void newreservabut1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newreservabut1ActionPerformed
    PedNewD newPed = new PedNewD();
    newPed.setSize(900, 560);
    newPed.setLocationRelativeTo(null);
    newPed.setVisible(true);
    newPed.pack();
    
  //  newPed.pack();// TODO add your handling code here:
}//GEN-LAST:event_newreservabut1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscartodobut;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton newreservabut;
    private javax.swing.JButton newreservabut1;
    // End of variables declaration//GEN-END:variables
}
