/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package test;

import gui.AppPrincipal;
import gui.dialog.ClientNewD;
import gui.dialog.ClientesConsultaUI;
import gui.dialog.OpcionesD;
import gui.dialog.PedNewD;
import gui.dialog.ProdNewD;
import gui.dialog.ReserNewD;
import gui.dialog.UserNewD;
import gui.internal.ProductosUI;
import java.awt.Dialog;
import java.awt.Dimension;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JRootPane;

/**
 *
 * @author Ivan C
 */
public class Apps extends javax.swing.JFrame {

    /**
     * Creates new form Apps
     */
    public Apps() {
        this.setUndecorated(true);
        //getRootPane().setWindowDecorationStyle(JRootPane.NONE);
        initComponents();
       

    }

    public Apps(int Us) {
        this();

        if (Us == 2) {
            this.jMenuAdmin.setVisible(false);
            this.jMenuItemNuevoProducto.setVisible(false);
            this.jMenuItemNuevoUsuario.setVisible(false);
        }


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jSeparator3 = new javax.swing.JSeparator();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuNuevo = new javax.swing.JMenu();
        jMenuItemPedido = new javax.swing.JMenuItem();
        jMenuItemReserva = new javax.swing.JMenuItem();
        jMenuItemCliente = new javax.swing.JMenuItem();
        jMenuAdmin = new javax.swing.JMenu();
        jMenuItemNuevoProducto = new javax.swing.JMenuItem();
        jMenuItemNuevoUsuario = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuProdMod = new javax.swing.JMenuItem();
        jMenuClientMod = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItemOpciones = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenuNuevo.setText("Nuevo");
        jMenuNuevo.setMargin(new java.awt.Insets(0, 5, 0, 5));

        jMenuItemPedido.setText("Pedido");
        jMenuItemPedido.setMargin(new java.awt.Insets(0, 5, 0, 5));
        jMenuItemPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPedidoActionPerformed(evt);
            }
        });
        jMenuNuevo.add(jMenuItemPedido);

        jMenuItemReserva.setText("Reserva");
        jMenuItemReserva.setMargin(new java.awt.Insets(0, 5, 0, 5));
        jMenuItemReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemReservaActionPerformed(evt);
            }
        });
        jMenuNuevo.add(jMenuItemReserva);

        jMenuItemCliente.setText("Cliente");
        jMenuItemCliente.setMargin(new java.awt.Insets(0, 5, 0, 5));
        jMenuItemCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemClienteActionPerformed(evt);
            }
        });
        jMenuNuevo.add(jMenuItemCliente);

        jMenuBar1.add(jMenuNuevo);

        jMenuAdmin.setText("Admin");
        jMenuAdmin.setMargin(new java.awt.Insets(0, 5, 0, 5));

        jMenuItemNuevoProducto.setText("Registrar Producto");
        jMenuItemNuevoProducto.setMargin(new java.awt.Insets(0, 5, 0, 5));
        jMenuItemNuevoProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNuevoProductoActionPerformed(evt);
            }
        });
        jMenuAdmin.add(jMenuItemNuevoProducto);

        jMenuItemNuevoUsuario.setText("Registrar Usuario");
        jMenuItemNuevoUsuario.setMargin(new java.awt.Insets(0, 5, 0, 5));
        jMenuItemNuevoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNuevoUsuarioActionPerformed(evt);
            }
        });
        jMenuAdmin.add(jMenuItemNuevoUsuario);
        jMenuAdmin.add(jSeparator1);

        jMenuProdMod.setText("Modificar Producto");
        jMenuProdMod.setMargin(new java.awt.Insets(0, 5, 0, 5));
        jMenuProdMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuProdModActionPerformed(evt);
            }
        });
        jMenuAdmin.add(jMenuProdMod);

        jMenuClientMod.setText("Modificar Cliente");
        jMenuClientMod.setMargin(new java.awt.Insets(0, 5, 0, 5));
        jMenuClientMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuClientModActionPerformed(evt);
            }
        });
        jMenuAdmin.add(jMenuClientMod);
        jMenuAdmin.add(jSeparator2);

        jMenuItemOpciones.setText("Opciones");
        jMenuItemOpciones.setMargin(new java.awt.Insets(0, 5, 0, 5));
        jMenuItemOpciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemOpcionesActionPerformed(evt);
            }
        });
        jMenuAdmin.add(jMenuItemOpciones);

        jMenuBar1.add(jMenuAdmin);

        setJMenuBar(jMenuBar1);
        try{
            AppPrincipal principalpanel = new AppPrincipal();
            principalpanel.setSize(1024, 768);
            this.add(principalpanel);
            this.setUndecorated(false);
        }catch(Exception ex){
            System.out.println("Problema con carga de panel en APPS");
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPedidoActionPerformed
        PedNewD newPed = new PedNewD();
        newPed.setSize(900, 560);
        newPed.setLocationRelativeTo(null);
        newPed.setVisible(true);
        newPed.pack();        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemPedidoActionPerformed

    private void jMenuItemClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemClienteActionPerformed
        ClientNewD clientedialog = new ClientNewD();
        clientedialog.setVisible(true);
        // clientedialog.pack();        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemClienteActionPerformed

    private void jMenuItemNuevoProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNuevoProductoActionPerformed
        ProdNewD newuserD = new ProdNewD();
        newuserD.setVisible(true);
        newuserD.setSize(450, 500);
        newuserD.setLocationRelativeTo(null);
    }//GEN-LAST:event_jMenuItemNuevoProductoActionPerformed

    private void jMenuItemNuevoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNuevoUsuarioActionPerformed
        UserNewD newuserD = new UserNewD();
        newuserD.setVisible(true);
        newuserD.setSize(450, 500);
        newuserD.setLocationRelativeTo(null);
    }//GEN-LAST:event_jMenuItemNuevoUsuarioActionPerformed

    private void jMenuProdModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuProdModActionPerformed

        ProductosUI wres;
        JDialog aux = new JDialog();
        boolean actualizado = false;

        try {
            wres = new ProductosUI(true);
            wres.setSize(400, 400);

            // wres.setVisible(true);
            aux.add(wres);
            aux.setMinimumSize(new Dimension(971, 710));
            aux.setModalityType(Dialog.ModalityType.APPLICATION_MODAL);
            aux.setLocationRelativeTo(null);
            aux.setVisible(true);




            //this.update(this.getGraphics());
        } catch (Exception ex) {
            Logger.getLogger(PedNewD.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jMenuProdModActionPerformed

    private void jMenuItemOpcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemOpcionesActionPerformed
        OpcionesD wres;

        boolean actualizado = false;

        try {
            wres = new OpcionesD();
            wres.setSize(400, 300);

            wres.setLocationRelativeTo(null);
            wres.setVisible(true);




            //this.update(this.getGraphics());
        } catch (Exception ex) {
            Logger.getLogger(PedNewD.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItemOpcionesActionPerformed

    private void jMenuItemReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemReservaActionPerformed
        ReserNewD wres = new ReserNewD();
        wres.setSize(740, 520);
        wres.setLocationRelativeTo(null);
        wres.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemReservaActionPerformed

    private void jMenuClientModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuClientModActionPerformed
        ClientesConsultaUI wres;
        JDialog aux = new JDialog();
        boolean actualizado = false;

        try {
            wres = new ClientesConsultaUI(true);
            wres.setSize(400, 400);

            // wres.setVisible(true);
            aux.add(wres);
            aux.setMinimumSize(new Dimension(971, 710));
            aux.setModalityType(Dialog.ModalityType.APPLICATION_MODAL);
            aux.setLocationRelativeTo(null);
            aux.setVisible(true);




            //this.update(this.getGraphics());
        } catch (Exception ex) {
            Logger.getLogger(PedNewD.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jMenuClientModActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Apps.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Apps.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Apps.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Apps.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new Apps().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenuAdmin;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuClientMod;
    private javax.swing.JMenuItem jMenuItemCliente;
    private javax.swing.JMenuItem jMenuItemNuevoProducto;
    private javax.swing.JMenuItem jMenuItemNuevoUsuario;
    private javax.swing.JMenuItem jMenuItemOpciones;
    private javax.swing.JMenuItem jMenuItemPedido;
    private javax.swing.JMenuItem jMenuItemReserva;
    private javax.swing.JMenu jMenuNuevo;
    private javax.swing.JMenuItem jMenuProdMod;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
