/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ProdNewD.java
 *
 * Created on 12-mar-2013, 23:16:56
 */
package gui.dialog;

import java.awt.Dialog;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import negocio.Control;
import negocio.ControlAdmin;
import negocio.ControlUsuario;
import negocio.FabricaUsuario;
import negocio.Producto;
import negocio.SingleControl;

/**
 *
 * @author Ivan C
 */
public class ProdNewD extends javax.swing.JDialog {

    Control control;
    FabricaUsuario fabrica;
    Producto producto;
    SingleControl single;
    private Producto prodmod;
    private String disponibilidadtmp;

    /**
     * Creates new form ProdNewD
     */
    public ProdNewD() {
        this.setModalityType(Dialog.ModalityType.APPLICATION_MODAL);
        single = new SingleControl();
        initComponents();
        setLocationRelativeTo(null);
//        fabrica = new FabricaUsuario();
        control = single.sesion();
        this.jButtonGuardarCambios.setVisible(false);
    }

    public ProdNewD(Producto prodtmp) {
        this();
        jButtonGuardar.setVisible(false);
        jButtonGuardarCambios.setVisible(true);
        prodmod = prodtmp;
        System.out.println(prodmod.getCod_bolsa() + "");
        jcodBolsa.setText(prodmod.getCod_bolsa() + "");
        jcaracteristicas.setText(prodmod.getCaract() + "");
        jcodIndividual.setText(prodmod.getCod_individual() + "");
        jcolor.setText(prodmod.getColor() + "");

        jestado.setText(prodmod.getEstado() + "");
        jlabelImagen.setText(prodmod.getImagen() + "");
        jnombre.setText(prodmod.getNombre() + "");
        jpais.setText(prodmod.getPais() + "");
        jprecio.setText(prodmod.getPrecio() + "");
        jtall.setText(prodmod.getTalla() + "");
        jtextura.setText(prodmod.getTextura() + "");
        disponibilidadtmp = prodmod.getDisponibilidad();


        /*   if (prodmod.getSexo().equals("UNISEX")) {
         jcombosexo.setSelectedIndex(0);
         } else if (prodmod.getSexo().equals("MASCULINO")) {
         jcombosexo.setSelectedIndex(1);
         } else if (prodmod.getSexo().equals("FEMENINO")) {
         jcombosexo.setSelectedIndex(2);
         }*/

        setModalityType(Dialog.ModalityType.APPLICATION_MODAL);
        this.jcodIndividual.setVisible(false);
        this.jLabel1.setVisible(false);
        this.jButtonGuardar.setVisible(false);
        this.setTitle("Actualizar Producto");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jcodIndividual = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jcodBolsa = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtextura = new javax.swing.JTextField();
        jcolor = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jnombre = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jestado = new javax.swing.JTextField();
        jcaracteristicas = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jtall = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jpais = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jprecio = new javax.swing.JTextField();
        jButtonSelImagen = new javax.swing.JButton();
        jButtonGuardar = new javax.swing.JButton();
        jcombosexo = new javax.swing.JComboBox();
        jlabelImagen = new javax.swing.JLabel();
        jButtonGuardarCambios = new javax.swing.JButton();

        setTitle("Nuevo Producto");
        setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);

        jcodIndividual.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jcodIndividualFocusLost(evt);
            }
        });
        jcodIndividual.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jcodIndividualKeyReleased(evt);
            }
        });

        jLabel1.setText("Codigo Producto");

        jLabel3.setText("Codigo Bolsa");

        jcodBolsa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jcodBolsaFocusLost(evt);
            }
        });
        jcodBolsa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jcodBolsaKeyReleased(evt);
            }
        });

        jLabel4.setText("Textura");

        jtextura.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtexturaKeyReleased(evt);
            }
        });

        jcolor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jcolorKeyReleased(evt);
            }
        });

        jLabel5.setText("Color");

        jLabel6.setText("Nombre");

        jnombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jnombreKeyReleased(evt);
            }
        });

        jLabel7.setText("Estado");

        jestado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jestadoKeyReleased(evt);
            }
        });

        jcaracteristicas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jcaracteristicasKeyReleased(evt);
            }
        });

        jLabel8.setText("Caracteristicas");

        jLabel9.setText("Talla");

        jtall.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtallKeyReleased(evt);
            }
        });

        jLabel10.setText("Pais Representa");

        jpais.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jpaisKeyReleased(evt);
            }
        });

        jLabel11.setText("Sexo");

        jLabel13.setText("Precio");

        jprecio.setText("0");
        jprecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jprecioKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jprecioKeyTyped(evt);
            }
        });

        jButtonSelImagen.setText("Seleccionar Imagen");
        jButtonSelImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSelImagenActionPerformed(evt);
            }
        });

        jButtonGuardar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonGuardar.setText("GUARDAR");
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });

        jcombosexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "UNISEX", "MASCULINO", "FEMENINO" }));

        jlabelImagen.setText("/");

        jButtonGuardarCambios.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonGuardarCambios.setText("Guardar Cambios");
        jButtonGuardarCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarCambiosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel3))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(66, 66, 66)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jpais, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                                            .addComponent(jestado, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                                            .addComponent(jcaracteristicas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jtextura)
                                                .addComponent(jcolor)
                                                .addComponent(jnombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE))
                                            .addComponent(jprecio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                                            .addComponent(jtall, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                                            .addComponent(jcombosexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jcodBolsa, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                                .addComponent(jcodIndividual, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonGuardarCambios))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonSelImagen, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlabelImagen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(140, 140, 140))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcodIndividual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcodBolsa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcolor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtextura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcaracteristicas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jestado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtall, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jcombosexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jpais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jprecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jlabelImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSelImagen)
                        .addContainerGap(62, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonGuardarCambios, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jButtonSelImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSelImagenActionPerformed
    CamaraNewImage imagedialog = new CamaraNewImage(jlabelImagen);
    imagedialog.setVisible(true);
}//GEN-LAST:event_jButtonSelImagenActionPerformed

private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
// TODO add your handling code here:
    producto = new Producto();
    producto.setCod_individual(jcodIndividual.getText().toUpperCase());
    producto.setCod_bolsa(jcodBolsa.getText().toUpperCase());
    producto.setColor(jcolor.getText().toUpperCase());
    producto.setCaract(jcaracteristicas.getText().toUpperCase());
    producto.setEstado(jestado.getText().toUpperCase());
    producto.setNombre(jnombre.getText().toUpperCase());
    producto.setPais(jpais.getText().toUpperCase());
    producto.setPrecio(Integer.parseInt(jprecio.getText()));
    producto.setSexo(jcombosexo.getSelectedItem().toString());
    producto.setTalla(jtall.getText().toUpperCase());
    producto.setTextura(jtextura.getText().toUpperCase());
    try {
        control.insertarProducto(producto);
        this.dispose();
    } catch (SQLException ex) {
        Logger.getLogger(ProdNewD.class.getName()).log(Level.SEVERE, null, ex);
    }
}//GEN-LAST:event_jButtonGuardarActionPerformed

    private void jButtonGuardarCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarCambiosActionPerformed
        producto = new Producto();
        producto.setCod_individual(jcodIndividual.getText().toUpperCase());
        producto.setCod_bolsa(jcodBolsa.getText().toUpperCase());
        producto.setColor(jcolor.getText().toUpperCase());
        producto.setCaract(jcaracteristicas.getText().toUpperCase());
        producto.setEstado(jestado.getText().toUpperCase());
        producto.setNombre(jnombre.getText().toUpperCase());
        producto.setPais(jpais.getText().toUpperCase());
        producto.setPrecio(Integer.parseInt(jprecio.getText()));
        producto.setSexo(jcombosexo.getSelectedItem().toString());
        producto.setTalla(jtall.getText().toUpperCase());
        producto.setTextura(jtextura.getText().toUpperCase());
        producto.setDisponibilidad(disponibilidadtmp);
        
        try {
            control.actualizarProducto(producto);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(ProdNewD.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonGuardarCambiosActionPerformed

    private void jcodIndividualKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcodIndividualKeyReleased
    }//GEN-LAST:event_jcodIndividualKeyReleased

    private void jcodBolsaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcodBolsaKeyReleased
    }//GEN-LAST:event_jcodBolsaKeyReleased

    private void jnombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jnombreKeyReleased
        String cadena = jnombre.getText().toUpperCase();
        jnombre.setText(cadena);
        jnombre.repaint();        // TODO add your handling code here:
    }//GEN-LAST:event_jnombreKeyReleased

    private void jcolorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcolorKeyReleased
        String cadena = jcolor.getText().toUpperCase();
        jcolor.setText(cadena);
        jcolor.repaint();          // TODO add your handling code here:
    }//GEN-LAST:event_jcolorKeyReleased

    private void jtexturaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtexturaKeyReleased
        String cadena = jtextura.getText().toUpperCase();
        jtextura.setText(cadena);
        jtextura.repaint();          // TODO add your handling code here:
    }//GEN-LAST:event_jtexturaKeyReleased

    private void jcaracteristicasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcaracteristicasKeyReleased
        String cadena = jcaracteristicas.getText().toUpperCase();
        jcaracteristicas.setText(cadena);
        jcaracteristicas.repaint();          // TODO add your handling code here:
    }//GEN-LAST:event_jcaracteristicasKeyReleased

    private void jestadoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jestadoKeyReleased
        String cadena = jestado.getText().toUpperCase();
        jestado.setText(cadena);
        jestado.repaint();          // TODO add your handling code here:
    }//GEN-LAST:event_jestadoKeyReleased

    private void jtallKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtallKeyReleased
        String cadena = jtall.getText().toUpperCase();
        jtall.setText(cadena);
        jtall.repaint();          // TODO add your handling code here:
    }//GEN-LAST:event_jtallKeyReleased

    private void jpaisKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jpaisKeyReleased
        String cadena = jpais.getText().toUpperCase();
        jpais.setText(cadena);
        jpais.repaint();          // TODO add your handling code here:
    }//GEN-LAST:event_jpaisKeyReleased

    private void jprecioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jprecioKeyReleased
        char caracter = evt.getKeyChar();
        if (((caracter < '0')
                || (caracter > '9'))
                && (caracter != evt.VK_BACK_SPACE)) {
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jprecioKeyReleased

    private void jcodIndividualFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jcodIndividualFocusLost
        String cadena = jcodIndividual.getText().toUpperCase();
        jcodIndividual.setText(cadena);
        jcodIndividual.repaint();
    }//GEN-LAST:event_jcodIndividualFocusLost

    private void jcodBolsaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jcodBolsaFocusLost
        String cadena = jcodBolsa.getText().toUpperCase();
        jcodBolsa.setText(cadena);
        jcodBolsa.repaint();
    }//GEN-LAST:event_jcodBolsaFocusLost

    private void jprecioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jprecioKeyTyped
        char caracter = evt.getKeyChar();
        if (((caracter < '0')
                || (caracter > '9'))
                && (caracter != evt.VK_BACK_SPACE)) {
            evt.consume();
        }     
    }//GEN-LAST:event_jprecioKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProdNewD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProdNewD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProdNewD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProdNewD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProdNewD().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JButton jButtonGuardarCambios;
    private javax.swing.JButton jButtonSelImagen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jcaracteristicas;
    private javax.swing.JTextField jcodBolsa;
    private javax.swing.JTextField jcodIndividual;
    private javax.swing.JTextField jcolor;
    private javax.swing.JComboBox jcombosexo;
    private javax.swing.JTextField jestado;
    private javax.swing.JLabel jlabelImagen;
    private javax.swing.JTextField jnombre;
    private javax.swing.JTextField jpais;
    private javax.swing.JTextField jprecio;
    private javax.swing.JTextField jtall;
    private javax.swing.JTextField jtextura;
    // End of variables declaration//GEN-END:variables
}
