/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ClientNew.java
 *
 * Created on 12-mar-2013, 19:45:10
 */
package gui.dialog;

import java.awt.Dialog;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import negocio.Cliente;
import negocio.Consultas;
import negocio.ControlUsuario;
import negocio.RefCliente;
import negocio.RefClienteCliente;

/**
 *
 * @author Ivan C
 */
public class ReferenceNewD extends javax.swing.JDialog {

    RefCliente ref;
    ControlUsuario control;
    ArrayList<RefCliente> referencias;
    JTextArea textArea;
    Cliente cliente;
    Consultas con;
    ClientesConsultaReferD auxRef;

    /** Creates new form ClientNew */
    public ReferenceNewD(RefCliente r, ArrayList refs, JTextArea lista, Cliente cliente, ClientesConsultaReferD aux) {
        initComponents();
        this.setModalityType(Dialog.ModalityType.APPLICATION_MODAL);
        control = new ControlUsuario();
        ref = r;
        referencias = refs;
        this.cliente = cliente;
        textArea = lista;
        setLocationRelativeTo(null);
        con = new Consultas();
        auxRef = aux;
    }

    private ReferenceNewD() {
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField6 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        apellidos = new javax.swing.JTextField();
        direccion = new javax.swing.JTextField();
        telefono = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        cedula = new javax.swing.JTextField();

        jTextField6.setText("jTextField6");

        setTitle("Agregar Referencia");
        setAlwaysOnTop(true);
        setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Nombres");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Apellidos");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Direccion");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Telefono Fijo");

        nombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });
        nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nombreKeyReleased(evt);
            }
        });

        apellidos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        direccion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        telefono.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        telefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                telefonoKeyTyped(evt);
            }
        });

        jButton2.setText("GUARDAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Documento");

        cedula.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cedulaFocusLost(evt);
            }
        });
        cedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cedulaKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1))
                        .addGap(81, 81, 81)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(apellidos, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                            .addComponent(nombre, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                            .addComponent(telefono, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                            .addComponent(direccion, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)))
                    .addComponent(jLabel6)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(cedula, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)))
                .addGap(65, 65, 65))
            .addGroup(layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(154, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(85, 85, 85)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_nombreActionPerformed

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
// TODO add your handling code here:
    Boolean exis = false;

    //ArrayList<RefCliente> r = control.consultarReferenciaPorCedula(cedula.getText());

    for (Iterator<RefCliente> it = referencias.iterator(); it.hasNext();) {
        RefCliente refCliente = it.next();
        if (refCliente.getCedula().equals(cedula.getText())) {
            exis = true;
        }
    }


    if (!exis) {
        ref.setNombre(nombre.getText().toUpperCase());
        ref.setCedula(cedula.getText().toUpperCase());
        ref.setDireccion(direccion.getText().toUpperCase());
        ref.setTelefono(telefono.getText().toUpperCase());
        ref.setApellido(apellidos.getText().toUpperCase());
        referencias.add(ref);
        if(textArea != null){
            textArea.setText(textArea.getText() + "\n" + ref.getNombre() + " " + ref.getApellido());
        }
        if(cliente != null){
                try {
                    RefClienteCliente rff = new RefClienteCliente();
                    rff.setIdCliente(cliente.getCedula());
                    rff.setIdRef(ref.getCedula());
                    if(con.verReferenciaPorCedula(ref.getCedula()).isEmpty()){
                        control.insertarReferencia(ref);
                    }
                    control.agregarReferenciaCliente(rff);
                    JOptionPane.showMessageDialog(this, "Referencia agregada correctamente");
                } catch (SQLException ex) {
                    Logger.getLogger(ReferenceNewD.class.getName()).log(Level.SEVERE, null, ex);
                } catch (Exception ex) {
                    Logger.getLogger(ReferenceNewD.class.getName()).log(Level.SEVERE, null, ex);
                }
        }
        if(auxRef != null){
            auxRef.eliminarTabla();
            auxRef.verTabla(referencias);
        }
        this.dispose();
    } else {
        JOptionPane.showMessageDialog(this, "La referencia ya está asociada a este usuario, por favor intente de nuevo");
        this.dispose();
    }

}//GEN-LAST:event_jButton2ActionPerformed

private void telefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telefonoKeyTyped
// TODO add your handling code here:
    char caracter = evt.getKeyChar();
    if (((caracter < '0')
            || (caracter > '9'))
            && (caracter != evt.VK_BACK_SPACE)) {
        evt.consume();
    }
}//GEN-LAST:event_telefonoKeyTyped

private void cedulaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cedulaFocusLost
// TODO add your handling code here:
    try {
        ArrayList<RefCliente> r = control.consultarReferenciaPorCedula(cedula.getText());
        RefCliente ref2 = null;
        if(r.get(0).getCedula().equals(cedula.getText()))ref2 = r.get(0);
        if (ref2.getCedula() != null) {
            telefono.setText(ref2.getTelefono());
            nombre.setText(ref2.getNombre());
            apellidos.setText(ref2.getApellido());
            direccion.setText(ref2.getDireccion());
            cedula.setEditable(false);
            telefono.setEditable(false);
            apellidos.setEditable(false);
            direccion.setEditable(false);
            nombre.setEditable(false);
        }
    } catch (Exception e) {
        Logger.getLogger(ReferenceNewD.class.getName()).log(Level.WARNING, null, e);
    }
}//GEN-LAST:event_cedulaFocusLost

private void cedulaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cedulaKeyReleased
    char caracter = evt.getKeyChar();
    if (((caracter < '0')
            || (caracter > '9'))
            && (caracter != evt.VK_BACK_SPACE)) {
        evt.consume();
    }// TODO add your handling code here:
}//GEN-LAST:event_cedulaKeyReleased

private void nombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombreKeyReleased
    String cadena = nombre.getText().toUpperCase();
    nombre.setText(cadena);
    nombre.repaint();
}//GEN-LAST:event_nombreKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReferenceNewD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReferenceNewD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReferenceNewD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReferenceNewD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ReferenceNewD().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apellidos;
    private javax.swing.JTextField cedula;
    private javax.swing.JTextField direccion;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField telefono;
    // End of variables declaration//GEN-END:variables
}
